name: presence
description: presence silo for the LYNX Bus Routing system.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  contracts:
    path: ../contracts
  riverpod: ^2.5.1
  rxdart: ^0.27.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.0
  geolocator: ^10.1.0
  geofencing: ^0.1.1
